apiVersion: v1
kind: Service
metadata:
  name: fiap-fase-3-service
  labels:
    app: fiap-fase-3
spec:
  selector:
    app: fiap-fase-3 
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: https
    port: 443
    targetPort: 8080
  type: LoadBalancer