apiVersion: v1
kind: Service
metadata:
  name: produtos-service
  labels:
    app: produtos
spec:
  selector:
    app: produtos
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: https
    port: 443
    targetPort: 8080
  type: LoadBalancer