apiVersion: apps/v1 
kind: Deployment
metadata:
  name: produtos
  labels: 
     app: produtos
spec:
  selector:
    matchLabels:
      app: produtos
      version: v01
  template:
    metadata:
      labels:
        app: produtos
        version: v01
    spec:
      serviceAccountName: produtos-account
      imagePullSecrets: 
        - name: docker-auth
      restartPolicy: Always
      containers:
      - name: produtos
        image: DOCKER_IMAGE
        imagePullPolicy: Always
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "200Mi"
            cpu: "200m"
        ports:
        - containerPort: 80
        env: 
        - name: "ASPNETCORE_ENVIROMENT"
          value: "Development"
# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: produtos-pod
# spec:
#   containers:
#   - name: produtos
#     image: DOCKER_IMAGE
#     resources:
#       requests:
#         memory: "50Mi"
#       limits:
#         memory: "100Mi"
#     ports:
#     - containerPort: 80
#     env: 
#     - name: "ASPNETCORE_ENVIROMENT"
#       value: "Development"