apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: produtos-hpa
  labels: 
     app: produtos
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: produtos-deployment
  # Compare this snippet from k8s/app-deployment.yaml:
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70